### ISSUE TITLE
major bump of iam-assumable-role breaks code

### ISSUE THREAD

**Issue by tbugfinder** [antonbabenko/serverless.tf-playground#2]
https://github.com/antonbabenko/serverless.tf-playground/blob/09a33db0440c63d10e4f0a96d2714f58f157fbd1/hashitalks2021/api_gateway_put_events_to_eventbridge_role.tf#L2

The major version change of iam-assumable-role breaks the codebase, as module versions are not pinned to a specific version.

**Comment by antonbabenko** [comment]
Good catch! I am in the process of updating all repositories and dependencies since the large update a couple of days ago (name of outputs changed to be without `this_`).

Meanwhile, you can just replace `this_`.

Ref: https://github.com/terraform-aws-modules/terraform-aws-iam/pull/150

**Comment by antonbabenko** [comment]
This repository is now fixed.
